experimental_monorepo_root = true

[tools]
node = "24"

[tasks]
  [tasks."dev"]
  run = { task = "//projects/...:dev" }

  [tasks.build]
  run = { task = "//projects/...:build" }

  [tasks.lint]
  run = [
    { tasks = [ "lint:types", "lint:es", "lint:style" ]}
  ]

  [tasks."lint:types"]
  run = { task = "//projects/...:lint:types" }

  [tasks."lint:es"]
  run = "eslint"

  [tasks."lint:style"]
  run = "stylelint \"**/*.{css,scss}\""

  [tasks.fix]
  run = [
    { tasks = [ "fix:es", "fix:style" ]}
  ]

  [tasks."fix:es"]
  run = "eslint --fix"

  [tasks."fix:style"]
  run = "stylelint --fix \"**/*.{css,scss}\""

  [tasks.test]
  run = { task = "//projects/...:test" }

  [tasks.test-lang]
  run = { task = "//projects/...:test-lang" }

  [tasks.testui]
  run = { task = "//projects/...:testui" }

  [tasks.clean]
  run = "git clean -dX --exclude=\"!.env\" --exclude=\"!mise.local.toml\" --force"

  [tasks.refresh]
  depends = [ "clean" ]
  run = [
    "rm --force ./pnpm-lock.yaml",
    "corepack enable",
    "corepack up",
    "pnpm install"
  ]

[hooks]
postinstall = [
  "corepack enable",
  "pnpm install --frozen-lockfile",
]

[env]
_.path = "{{config_root}}/node_modules/.bin"

[settings]
jobs = 8
task.monorepo_depth = 2
npm.package_manager = "pnpm"

# Required for hooks & monorepo tasks as of 2026.01
# https://mise.jdx.dev/hooks.html
# https://mise.jdx.dev/tasks/monorepo.html
experimental = true
