[tools]
node = "24"

[tasks]
  [tasks."dev"]
  run = "vite dev"

  [tasks.build]
  run = "vite build"

  [tasks.lint]
  run = [
    { tasks = [ "lint:types", "lint:es", "lint:style" ]}
  ]

  [tasks."lint:types"]
  run = "tsc --noEmit"

  [tasks."lint:es"]
  run = "eslint"

  [tasks."lint:style"]
  run = "stylelint \"**/*.{css,scss}\""

  [tasks.fix]
  run = [
    { tasks = [ "fix:es", "fix:style" ]}
  ]

  [tasks."fix:es"]
  run = "eslint --fix"

  [tasks."fix:style"]
  run = "stylelint --fix \"**/*.{css,scss}\""

  [tasks.test]
  run = "vitest run"

  [tasks.test-lang]
  run = "vitest test lang"
  env = { CHECK_LANGUAGES = "true" }

  [tasks.testui]
  run = { tasks = [ "dev", "testui:*" ]}
  env = { DOM_PREVIEW = "true" }

  [tasks."testui:unit"]
  run = "vitest --ui"

  [tasks."testui:dom-preview"]
  run = "dom-preview --proxy-to=http://localhost:5173"

  [tasks.clean]
  run = "git clean -dX --exclude=\"!.env\" --exclude=\"!mise.local.toml\" --force"

  [tasks.refresh]
  depends = [ "clean" ]
  run = [
    "rm --force ./pnpm-lock.yaml",
    "corepack enable",
    "corepack up",
    "pnpm install"
  ]

[hooks]
postinstall = [
  "corepack enable",
  "pnpm install --frozen-lockfile",
]

[env]
_.path = "./node_modules/.bin"

[settings]
jobs = 8
npm.package_manager = "pnpm"

# Required for hooks as of 2025.10
# https://mise.jdx.dev/hooks.html
experimental = true
