[tasks]
  [tasks.dev]
  run = [{ tasks = [ "dev:app", "dev:ngrok" ]}]

  [tasks."dev:app"]
  run = "next dev"

  [tasks.start]
  run = "next start"

  [tasks.build]
  run = "next build"

  [tasks."lint:types"]
  run = "tsc --noEmit"

  [tasks.prebuild]
  run = "prisma generate"
  raw = true # Required for the spinner and interactive UIs

[env]
_.path = "{{config_root}}/node_modules/.bin"

[settings]
jobs = 8

# Required for hooks & monorepo tasks as of 2026.01
# https://mise.jdx.dev/hooks.html
# https://mise.jdx.dev/tasks/monorepo.html
experimental = true
