name: GitHub Actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - published

permissions:
  contents: read

env:
  DATABASE_URL: "postgresql://illumina:illumina@localhost:5432/illumina"
  NEXT_PUBLIC_URL: "https://localhost:3000"
  COOKIE_PASSWORD: "REPLACE_ME_ON_PRODUCTION_h3tr#@B"

jobs:
  build-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: jdx/mise-action@146a28175021df8ca24f8ee1828cc2a60f980bd5 # v3.5.1
        with:
          install: true
          cache: true

      - run: mise build

      # TODO disabled until all the TypeScript & lint errors are eliminated
      #- run: mise lint

      # Type check by `tsc --noEmit` is skipped as of now

      - name: run ESLint only on changed files
        uses: tj-actions/eslint-changed-files@536c35c8184b8bbd361d3703aa63439e0895c340 # v25.3.2
        with:
          escape_paths: false # for files including `$` in their file name
          skip_annotations: true

      - run: mise lint:style

      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: dist
          path: dist
          if-no-files-found: error
          retention-days: 1
          include-hidden-files: true

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: jdx/mise-action@146a28175021df8ca24f8ee1828cc2a60f980bd5 # v3.5.1
        with:
          install: true
          cache: true

      - run: mise test

  test-langs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: jdx/mise-action@146a28175021df8ca24f8ee1828cc2a60f980bd5 # v3.5.1
        with:
          install: true
          cache: true

      - run: mise test-lang
        continue-on-error: true
